export const SERVICES = [
    {
        id: 1,
        nameservice: 'Water Quality Analysis',
        productcode: 'WQA001',
        price: 500000.0,
        summary: 'Analyze the water quality in your koi pond.',
        content: 'Detailed analysis of pH, ammonia, nitrate, and other essential water parameters to ensure a healthy environment for your koi.',
        status: 'Available',
        image_path: 'services-images/water-quality-analysis.png',
    },
    {
        id: 2,
        nameservice: 'Koi Health Checkup',
        productcode: 'KHC002',
        price: 700000.0,
        summary: 'Comprehensive health check for your koi.',
        content: 'Includes physical examination, parasite checks, and guidance on nutrition and care.',
        status: 'Available',
        image_path: 'services-images/koi-health-checkup.png',
    },
    {
        id: 3,
        nameservice: 'Disease Treatment',
        productcode: 'DT003',
        price: 1000000.0,
        summary: 'Effective treatment for koi diseases.',
        content: 'Diagnosis and treatment of common koi diseases such as ulcers, fin rot, and infections.',
        status: 'Available',
        image_path: 'services-images/disease-treatment.png',
    },
    {
        id: 4,
        nameservice: 'Pond Design Consultation',
        productcode: 'PDC004',
        price: 1500000.0,
        summary: 'Optimize your pond design for koi health.',
        content: 'Expert advice on pond layout, filtration systems, and aeration for a thriving koi environment.',
        status: 'Available',
        image_path: 'services-images/pond-design-consultation.png',
    },
    {
        id: 5,
        nameservice: 'Emergency Koi Care',
        productcode: 'EKC005',
        price: 2000000.0,
        summary: '24/7 emergency care for your koi.',
        content: 'Rapid response for koi in critical condition, including transport and on-site treatment.',
        status: 'Available',
        image_path: 'services-images/emergency-koi-care.png',
    },
]
